//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chek
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Nickname { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Products Products { get; set; }
    }
}
