//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopushok.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Chek = new HashSet<Chek>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public string Cost { get; set; }
        public string Image { get; set; }
        public string ProductType { get; set; }
        public string Count { get; set; }
        public string Fullname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chek> Chek { get; set; }
        public virtual Salesman Salesman { get; set; }
        public string ImagePath
        {
            get
            {
                if (Image.Length > 0)
                {
                    return @".." + Image.ToString();
                }
                else
                {
                    return @"..\products\picture.png";
                }
            }
        }
    }
}
